-- Apache NEC-IDS
-- plugin_id: 8068
DELETE FROM plugin WHERE id = "8068";
DELETE FROM plugin_sid where plugin_id = "8068";
INSERT IGNORE INTO plugin (id, type, name, description) VALUES (8068, 1, 'NEC-IDS', 'NEC-IDS');

-- plugin sids...
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 24, NULL, NULL, 'NEC-IDS : Detects basic obfuscated JavaScript script injections');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 25, NULL, NULL, 'NEC-IDS : Detects obfuscated JavaScript script injections');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 26, NULL, NULL, 'NEC-IDS : Detects JavaScript cookie stealing and redirection attempts');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 27, NULL, NULL, 'NEC-IDS : Detects data: URL injections, VBS injections and common URI schemes');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 20, NULL, NULL, 'NEC-IDS : Detects JavaScript language constructs');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 21, NULL, NULL, 'NEC-IDS : Detects very basic XSS probings');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 22, NULL, NULL, 'NEC-IDS : Detects advanced XSS probings via Script(), RexExp, constructors and XML namespaces');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 23, NULL, NULL, 'NEC-IDS : Detects JavaScript location/document property access and window access obfuscation');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 28, NULL, NULL, 'NEC-IDS : Detects IE firefoxurl injections, cache poisoning attempts and local file inclusion/execution');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 29, NULL, NULL, 'NEC-IDS : Detects bindings and behavior injections');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 4, NULL, NULL, 'NEC-IDS : Detects url-, name-, JSON, and referrer-contained payload attacks');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 8, NULL, NULL, 'NEC-IDS : Detects self-executing JavaScript functions');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 59, NULL, NULL, 'NEC-IDS : Detects code injection attempts 2/3');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 58, NULL, NULL, 'NEC-IDS : Detects code injection attempts 1/3');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 55, NULL, NULL, 'NEC-IDS : Detects MSSQL code execution and information gathering attempts');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 54, NULL, NULL, 'NEC-IDS : Detects Postgres pg_sleep injection, waitfor delay attacks and database shutdown attempts');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 57, NULL, NULL, 'NEC-IDS : Detects MySQL comment-/space-obfuscated injections and backtick termination');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 56, NULL, NULL, 'NEC-IDS : Detects MATCH AGAINST, MERGE, EXECUTE IMMEDIATE and HAVING injections');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 51, NULL, NULL, 'NEC-IDS : Detects MySQL UDF injection and other data/structure manipulation attempts');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 50, NULL, NULL, 'NEC-IDS : Detects SQL benchmark and sleep injection attempts including conditional queries');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 53, NULL, NULL, 'NEC-IDS : Detects MySQL and PostgreSQL stored procedure/function injections');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 52, NULL, NULL, 'NEC-IDS : Detects MySQL charset switch and MSSQL DoS attempts');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 88, NULL, NULL, 'NEC-IDS : Detects php remote file include attempt 5');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 89, NULL, NULL, 'NEC-IDS : SQL Password Change attempt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 82, NULL, NULL, 'NEC-IDS : Detects /etc/shadow inclusion attempts');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 83, NULL, NULL, 'NEC-IDS : Detects php remote file include attempt 1');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 80, NULL, NULL, 'NEC-IDS : Generic SQL injection attemp');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 81, NULL, NULL, 'NEC-IDS : Generic SQL injection attemp');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 86, NULL, NULL, 'NEC-IDS : Detects php remote file include attempt 4');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 87, NULL, NULL, 'NEC-IDS : Detects php remote file include attempt 5');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 84, NULL, NULL, 'NEC-IDS : Detects php remote file include attempt 2');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 85, NULL, NULL, 'NEC-IDS : Detects php remote file include attempt 3');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 3, NULL, NULL, 'NEC-IDS : finds unquoted attribute breaking injections');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 7, NULL, NULL, 'NEC-IDS : Detects JavaScript with(), ternary operators and XML predicate attacks');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 39, NULL, NULL, 'NEC-IDS : Detects nullbytes and other dangerous characters');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 38, NULL, NULL, 'NEC-IDS : Detects possibly malicious html elements including some attributes');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 33, NULL, NULL, 'NEC-IDS : Detects obfuscated script tags and XML wrapped HTML');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 32, NULL, NULL, 'NEC-IDS : Detects possible event handlers');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 31, NULL, NULL, 'NEC-IDS : Detects common XSS concatenation patterns 2/2');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 30, NULL, NULL, 'NEC-IDS : Detects common XSS concatenation patterns 1/2');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 37, NULL, NULL, 'NEC-IDS : Detects base href injections and XML entity injections');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 35, NULL, NULL, 'NEC-IDS : Detects common comment types');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 34, NULL, NULL, 'NEC-IDS : Detects attributes in closing tags and conditional compilation tokens');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 60, NULL, NULL, 'NEC-IDS : Detects code injection attempts 3/3');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 61, NULL, NULL, 'NEC-IDS : Detects url injections and RFE attempts');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 62, NULL, NULL, 'NEC-IDS : Detects common function declarations and special JS operators');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 63, NULL, NULL, 'NEC-IDS : Detects common mail header injections');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 64, NULL, NULL, 'NEC-IDS : Detects perl echo shellcode injection and LDAP vectors');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 65, NULL, NULL, 'NEC-IDS : Detects basic XSS DoS attempts');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 67, NULL, NULL, 'NEC-IDS : Detects unknown attack vectors based on PHPIDS Centrifuge detection');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 68, NULL, NULL, 'NEC-IDS : Finds attribute breaking injections including obfuscated attributes');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 69, NULL, NULL, 'NEC-IDS : Finds basic VBScript injection attempts');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 2, NULL, NULL, 'NEC-IDS : finds attribute breaking injections including whitespace attacks');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 6, NULL, NULL, 'NEC-IDS : Detects self contained xss via with(), common loops and regex to string conversion');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 91, NULL, NULL, 'NEC-IDS : Bash vulnerability Shellshock attemp detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 90, NULL, NULL, 'NEC-IDS : SQL Password Change attempt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 11, NULL, NULL, 'NEC-IDS : Detects specific directory and path traversal');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 10, NULL, NULL, 'NEC-IDS : Detects basic directory traversal');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 13, NULL, NULL, 'NEC-IDS : Detects halfwidth/fullwidth encoded unicode HTML breaking attempts');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 12, NULL, NULL, 'NEC-IDS : Detects etc/passwd inclusion attempts');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 15, NULL, NULL, 'NEC-IDS : Detects JavaScript DOM/miscellaneous properties and methods');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 14, NULL, NULL, 'NEC-IDS : Detects possible includes, VBSCript/JScript encodeed and packed functions');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 17, NULL, NULL, 'NEC-IDS : Detects JavaScript object properties and methods');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 16, NULL, NULL, 'NEC-IDS : Detects possible includes and typical script methods');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 19, NULL, NULL, 'NEC-IDS : Detects JavaScript string properties and methods');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 18, NULL, NULL, 'NEC-IDS : Detects JavaScript array properties and methods');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 48, NULL, NULL, 'NEC-IDS : Detects chained SQL injection attempts 1/2');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 49, NULL, NULL, 'NEC-IDS : Detects chained SQL injection attempts 2/2');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 46, NULL, NULL, 'NEC-IDS : Detects basic SQL authentication bypass attempts 3/3');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 47, NULL, NULL, 'NEC-IDS : Detects concatenated basic SQL injection and SQLLFI attempts');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 44, NULL, NULL, 'NEC-IDS : Detects basic SQL authentication bypass attempts 1/3');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 45, NULL, NULL, 'NEC-IDS : Detects basic SQL authentication bypass attempts 2/3');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 42, NULL, NULL, 'NEC-IDS : Detects classic SQL injection probings 1/2');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 43, NULL, NULL, 'NEC-IDS : Detects classic SQL injection probings 2/2');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 40, NULL, NULL, 'NEC-IDS : Detects MySQL comments, conditions and ch(a)r injections');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 41, NULL, NULL, 'NEC-IDS : Detects conditional SQL injection attempts');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 1, NULL, NULL, 'NEC-IDS : finds html breaking injections including whitespace attacks');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 5, NULL, NULL, 'NEC-IDS : Detects hash-contained xss payload attacks, setter usage and property overloading');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 9, NULL, NULL, 'NEC-IDS : Detects the IE octal, hex and unicode entities');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 77, NULL, NULL, 'NEC-IDS : Looking for intiger overflow attacks, these are taken from skipfish, except 2.2250738585072007e-308 is the "magic number" crash');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 76, NULL, NULL, 'NEC-IDS : Looking for basic sql injection. Common attack string for mysql, oracle and others.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 75, NULL, NULL, 'NEC-IDS : Looking for a format string attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 74, NULL, NULL, 'NEC-IDS : Detects remote code exectuion tests. Will match "ping -n 3 localhost" and "ping localhost -n 3" ');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 73, NULL, NULL, 'NEC-IDS : An attacker is trying to locate a file to read or write.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 72, NULL, NULL, 'NEC-IDS : Detects blind sqli tests using sleep() or benchmark().');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 71, NULL, NULL, 'NEC-IDS : finds malicious attribute injection attempts and MHTML attacks');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 70, NULL, NULL, 'NEC-IDS : Finds basic MongoDB SQL injection attempts');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100030, NULL, NULL, 'NEC-IDS : Paros scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100031, NULL, NULL, 'NEC-IDS : SiteSucker scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100033, NULL, NULL, 'NEC-IDS : SWebsecurifyScanner scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100032, NULL, NULL, 'NEC-IDS : Sputnik scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100016, NULL, NULL, 'NEC-IDS : SQLmap scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100017, NULL, NULL, 'NEC-IDS : Scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100014, NULL, NULL, 'NEC-IDS : Nsauditor scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100015, NULL, NULL, 'NEC-IDS : Paros scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100012, NULL, NULL, 'NEC-IDS : Nikto scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100013, NULL, NULL, 'NEC-IDS : Nmap scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100010, NULL, NULL, 'NEC-IDS : Nessus scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100011, NULL, NULL, 'NEC-IDS : Netsparker scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100034, NULL, NULL, 'NEC-IDS : ZmEu scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100018, NULL, NULL, 'NEC-IDS : Scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100019, NULL, NULL, 'NEC-IDS : Scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100029, NULL, NULL, 'NEC-IDS : Nmap scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100028, NULL, NULL, 'NEC-IDS : Morfeus Fucking Scanner User-Agent detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100023, NULL, NULL, 'NEC-IDS : DigExt User-Agent detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100022, NULL, NULL, 'NEC-IDS : DigExt scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100005, NULL, NULL, 'NEC-IDS : Acunetix scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100004, NULL, NULL, 'NEC-IDS : Acunetix scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100007, NULL, NULL, 'NEC-IDS : Dfind scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100006, NULL, NULL, 'NEC-IDS : Dfind scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100001, NULL, NULL, 'NEC-IDS : Havij User agent detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100000, NULL, NULL, 'NEC-IDS : Wget User agent detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100003, NULL, NULL, 'NEC-IDS : Acunetix scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100002, NULL, NULL, 'NEC-IDS : Nikto User agent detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100027, NULL, NULL, 'NEC-IDS : HTTrack User-Agent detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100026, NULL, NULL, 'NEC-IDS : DirBuster User-Agent detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100025, NULL, NULL, 'NEC-IDS : FOCA User-Agent detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100024, NULL, NULL, 'NEC-IDS : DTS Agent User-Agent detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100009, NULL, NULL, 'NEC-IDS : Morfeus scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100008, NULL, NULL, 'NEC-IDS : Havij scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100021, NULL, NULL, 'NEC-IDS : XSpider scanner attack detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (8068, 100020, NULL, NULL, 'NEC-IDS : XSpider scanner attack detected');
